version: '3.8'
services:
  nestjs-app:
    build: .
    ports:
      - '3001:3001'
    volumes:
      - uploads:/app/uploads
    env_file:
      - .env

    depends_on:
      - db
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: nestjs2
      POSTGRES_PASSWORD: mamank_travel1234
      POSTGRES_DB: mamank_travel
    ports:
      - '5433:5432'

volumes:
  postgres-data:
  uploads:

networks:
  app-network:
    driver: bridge
