# nginx/nginx.conf
events {}

http {
  server {
    listen 80;
    server_name business2berkah.com;
    return 301 https://$host$request_uri;
  }

  server {
    listen 443 ssl;
    server_name business2berkah.com;

    ssl_certificate /etc/letsencrypt/live/business2berkah.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/business2berkah.com/privkey.pem;

    location / {
      proxy_pass http://nestjs-app:3001;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}